---
title: "Reproducible Research: Peer Assessment 1"
author: "Corbin Thornbrough"
date: "Friday, August 15th, 2014"
output: html_document
---

Loading and preprocessing the data
```{r}
setwd("C:/Users/corbin.thornbrough/Documents/R/Reproducible Research/Quantified Self Peer Assessment/RepData_PeerAssessment1")
unzip("activity.zip")
activity<-read.csv("activity.csv")
activity$date<-as.Date(activity$date)
activity$steps<-as.numeric(activity$steps)
activity$interval<-as.numeric(activity$interval)
```


What is mean total number of steps taken per day?

```{r}
act.steps.agg<-aggregate(steps~date,activity,sum)
hist(act.steps.agg$steps, main="Histogram of Daily Steps", xlab="Steps")
mean(act.steps.agg$steps)
median(act.steps.agg$steps)
```

What is the average daily activity pattern?

```{r}
act.interval.agg<-aggregate(steps~interval,activity, mean)
plot(act.interval.agg$steps~act.interval.agg$interval, type="l", xlab="five-minute interval",
     ylab="steps averaged across all days", main="Plot of Average Steps by Interval")
act.interval.agg[which.max(act.interval.agg$steps),1]
```

Imputing missing values

```{r}
activity.mod<-activity
sum(is.na(activity.mod$steps))
activity.mod$steps<-with(activity.mod,ifelse(
  is.na(steps),
  ave(steps,interval,FUN=function(steps)mean(steps, na.rm=TRUE)),
  steps
  ))
mod.act.agg<-aggregate(steps~date,activity.mod,sum)
hist(mod.act.agg$steps, main="Histogram of Daily Steps", xlab="Steps")
mean(mod.act.agg$steps)
median(mod.act.agg$steps)
```


Are there differences in activity patterns between weekdays and weekends?
```{r}
require(lattice)
activity.mod$weekday<-ifelse(weekdays(activity.mod$date)=="Saturday" | weekdays(activity.mod$date)=="Sunday","weekend","weekday")
xyplot(activity.mod$steps~activity.mod$interval | activity.mod$weekday, activity.mod, type="h", ylab="Steps",xlab="Interval")
```
